upgrade is-executable binary

diff --git a/bin/is-executable b/bin/is-executable
--- a/bin/is-executable
+++ b/bin/is-executable
@@ -1,7 +1,51 @@
 #!/usr/bin/env bash
 
-if command -v "$1" >/dev/null 2>&1; then
+BIN_NAME=$(basename "$0")
+
+function usage {
+    echo "Usage:"
+    echo "$BIN_NAME [-q] command"
+    echo
+	echo "If the input command exists, this utility prints a green message confirming"
+    echo "the existence of the command, and exits with a success status code."
+	echo
+	echo "Otherwise, the utility prints a red message confirming that the command"
+	echo "does not exists, and exits with a failure status code."
+	echo
+    echo "COMMAND LINE OPTIONS:"
+	echo
+	echo "-q"
+	echo "    suppresses the printing of the summary message"
+    echo
+    exit 1
+}
+
+if [[ "$1" = "help" ]] || [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]; then
+	usage
+fi
+
+QUIET="FALSE"
+
+while getopts ':q' flag; do
+  case "${flag}" in
+	q) QUIET="TRUE";;
+  esac
+done
+
+shift $((OPTIND -1))
+
+COMMAND="$1"
+
+[[ -z "$COMMAND" ]] && "No input command specified!" && usage
+
+COLOR_OFF='\033[0m'      
+RED='\033[1;91m'
+GREEN='\033[1;92m'
+
+if command -v "$COMMAND" >/dev/null 2>&1; then
+	[[ "$QUIET" == "FALSE" ]] && echo -e "${GREEN}${COMMAND}: command exists${COLOR_OFF}"
 	exit 0
 else
+	[[ "$QUIET" == "FALSE" ]] && echo -e "${RED}${COMMAND}: command does not exist${COLOR_OFF}"
 	exit 1
 fi
