Enhance documentation of utilities

diff --git a/bin/is-evaluable b/bin/is-evaluable
--- a/bin/is-evaluable
+++ b/bin/is-evaluable
@@ -1,12 +1,39 @@
 #!/usr/bin/env bash
 
+# If one argument is provided, this utility succeeds if the argument can be evaluated,
+# otherwise it fails.
+
+# If three arguments are provided, this utility returns the second argument if the
+# first argument can be evaluated, otherwise it returns the third argument
+
+BIN_NAME=$(basename "$0")
+
+function usage {
+    echo "Usage:"
+    echo "$BIN_NAME expr [print_if_fail] [print_if_success]"
+    echo ""
+    echo "If one argument is provided, this utility succeeds if the"
+    echo "expression can be evaluated, otherwise it fails."
+    echo ""
+    echo "If three arguments are provided, this utility prints and"
+    echo "returns the second argumet if the first argument can be evaluated,"
+    echo "otherwise it prints and returns the third argument."
+    exit 1
+}
+
+if [[ $1 = "help" ]] || [[ $1 = "-h" ]] || [[ $1 = "--help" ]]; then
+  usage
+fi
+
+[ -z "$1" ] && usage
+
 if [ $# -eq 1 ]; then
   if eval "$1" > /dev/null 2>&1; then 
     exit 0
   else
     exit 1
   fi
-else
+elif [ $# -eq 3 ]; then
   if eval "$1" > /dev/null 2>&1; then
     echo -n "$2"
   else
